/**
 * Track detail content by slug (?track=…). Extend as you add tracks.
 */
window.TRACKS_DATA = {
  "work-burnout": {
    slug: "work-burnout",
    pageTitle: "Find Balance After Work Burnout",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/work-burnout.png",
    heroImageAlt: "",
    authorName: "Saeromi Kim, Ph.D.",
    authorRole: "Clinical Psychologist",
    authorAvatar: "/assets/images/Kim.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by  Saeromi Kim, Ph.D.",
    authorBioShort:
      "Saeromi Kim is an Assistant Clinical Director at UCLA, and also has a private clinical and consultation practice focused on stress, burnout, and sustainable emotional health.",
    authorDescriptionParagraphs: [
      "Let's face it, work can be stressful. So much is out of your control, and the ever-present demands, deadlines, quotas, and uncertainty can leave you feeling worn out.",
      "For both your body and mind, it's important to take the time to reset after a period of intense work stress. It can help replenish your energy and get you back to feeling like yourself—at work, at home, and in your relationships.",
    ],
    authorDescriptionClosing: "Let's get started.",
    authorBioFullParagraphs: [
      "Saeromi Kim is an Assistant Clinical Director at UCLA, and also has a private clinical and consultation practice focused on stress, burnout, and sustainable emotional health.",
      "At UCLA and in private practice, I work with adults who feel stretched thin by work and caregiving responsibilities. My approach blends cognitive behavioral therapy, mindfulness, and self-compassion so progress feels both realistic and sustainable.",
      "I made this track because burnout is not a personal failure; it is often a sign that your system has been overworked for too long. My goal is to help you rebuild rest, resilience, and a sense of agency one step at a time.",
    ],
    helps: [
      "Rest and recover",
      "Feel less stressed and more resilient",
      "Reconnect with joy",
    ],
    trackDetails: ["12 Carefully crafted activities"],
  },
  "beat-burnout-build-resilience": {
    slug: "beat-burnout-build-resilience",
    pageTitle: "Beat Burnout & Build Resilience",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/build-resilience.png",
    heroImageAlt: "",
    authorName: "Emma Seppälä, Ph.D.",
    authorRole: "Author of Track",
    authorAvatar: "/assets/images/Sepa.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Emma Seppala, Ph.D.",
    authorBioShort:
      "Emma Seppala teaches science-backed tools for sustainable performance and emotional resilience at work so high achievement does not come at the cost of well-being.",
    authorDescriptionParagraphs: [
      "Burnout can make every task feel heavier than it should. This track helps you interrupt that cycle by combining practical stress regulation with habits that restore your energy before you hit empty.",
      "You will build small, repeatable routines that support focus, emotional steadiness, and healthier boundaries so your performance can improve without sacrificing your well-being.",
    ],
    authorDescriptionClosing: "Let's build resilience you can actually maintain.",
    authorBioFullParagraphs: [
      "Emma Seppala teaches science-backed tools for sustainable performance and emotional resilience at work so high achievement does not come at the cost of well-being.",
      "My work bridges psychology and leadership, helping people perform at a high level without ignoring their mental and physical health. I care deeply about practical strategies that can fit into real, demanding schedules.",
      "I made this track to help you recover from burnout and build a stronger baseline so stress does not keep dictating how you feel at work and at home.",
    ],
    helps: [
      "Feel less stressed and more fulfilled",
      "Manage your energy better",
      "Maximize your resilience and productivity",
    ],
    trackDetails: ["10 Carefully crafted activities"],
  },
  "thrive-during-change-work": {
    slug: "thrive-during-change-work",
    pageTitle: "Thrive During Change at Work",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/change-work.png",
    heroImageAlt: "",
    authorName: "Taryn Marie, Ph.D.",
    authorRole: "Resilience Expert",
    authorAvatar: "/assets/images/Marie.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Taryn Marie, Ph.D.",
    authorBioShort:
      "Taryn Marie helps teams and professionals stay grounded, adaptable, and purpose-driven during transition, especially when uncertainty impacts confidence and clarity.",
    authorDescriptionParagraphs: [
      "Workplace change can trigger uncertainty, self-doubt, and emotional fatigue. This track gives you a clear process to stay steady when priorities shift and expectations keep moving.",
      "Through structured reflection and resilience exercises, you will learn to reframe difficult dynamics, protect your energy, and reconnect with what matters most in your work.",
    ],
    authorDescriptionClosing: "You can grow through change without losing yourself.",
    authorBioFullParagraphs: [
      "Taryn Marie helps teams and professionals stay grounded, adaptable, and purpose-driven during transition, especially when uncertainty impacts confidence and clarity.",
      "My approach combines evidence-based coping tools with strengths-focused coaching to help people move from reactive stress into intentional action.",
      "I made this track so you have dependable practices for staying clear and grounded even when your workplace environment feels unpredictable.",
    ],
    helps: [
      "Reframe challenging work dynamics",
      "Strengthen resilience during stressful times",
      "Feel more connected to your purpose",
    ],
    trackDetails: ["9 Carefully crafted activities"],
  },
  "find-your-flow-engaged-work": {
    slug: "find-your-flow-engaged-work",
    pageTitle: "Find Your Flow: Feel Engaged at Work",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/engaged-work.png",
    heroImageAlt: "",
    authorName: "Cara Bradley, Ph.D.",
    authorRole: "Author, Body-Mind Teacher",
    authorAvatar: "/assets/images/Bradley.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Cara Bradley, Ph.D.",
    authorBioShort:
      "Cara Bradley blends performance psychology and mindfulness to help people access calm, focused engagement in demanding work environments.",
    authorDescriptionParagraphs: [
      "When your attention is fragmented, work can feel draining and disconnected. This track helps you train your focus and nervous system so you can be present, effective, and less reactive.",
      "You will practice body-mind techniques that reduce stress overload, improve clarity, and support stronger day-to-day performance without constant mental strain.",
    ],
    authorDescriptionClosing: "Let's help you find a steadier, more energized flow state.",
    authorBioFullParagraphs: [
      "Cara Bradley blends performance psychology and mindfulness to help people access calm, focused engagement in demanding work environments.",
      "For years, I have taught practical methods for regulating stress and sharpening attention so people can feel more alive in their work instead of mentally depleted.",
      "I made this track to make flow feel trainable, not accidental, through short practices you can use throughout your workday.",
    ],
    helps: [
      "Increase clarity and calm",
      "Reduce effects of stress on body and mind",
      "Enhance performance",
    ],
    trackDetails: ["8 Carefully crafted activities"],
  },
  "feel-control-working-parent": {
    slug: "feel-control-working-parent",
    pageTitle: "Feel in Control as Working Parent",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/working-parent.png",
    heroImageAlt: "",
    authorName: "Karen Race, Ph.D.",
    authorRole: "Author of Mindful Parenting",
    authorAvatar: "/assets/images/Race.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Karen Race, Ph.D.",
    authorBioShort:
      "Karen Race supports working parents in creating sustainable routines, boundaries, and emotional balance while juggling professional and family demands.",
    authorDescriptionParagraphs: [
      "Balancing career demands and family responsibilities can feel relentless. This track helps you reset your priorities and build practical systems that reduce daily friction.",
      "You will use mindful planning, communication, and boundary-setting tools to create more stability at home and at work so you can feel less pulled in every direction.",
    ],
    authorDescriptionClosing: "Let's make your responsibilities feel manageable again.",
    authorBioFullParagraphs: [
      "Karen Race supports working parents in creating sustainable routines, boundaries, and emotional balance while juggling professional and family demands.",
      "I have spent years supporting families through stress, transition, and role overload. My goal is to turn good intentions into practical routines that actually hold up in busy weeks.",
      "I made this track to help you regain a sense of control while protecting what matters most in both your professional and family life.",
    ],
    helps: [
      "Reconnect with your priorities",
      "Balance your work and family life",
      "Feel less stressed",
    ],
    trackDetails: ["10 Carefully crafted activities"],
  },
  "find-your-calling": {
    slug: "find-your-calling",
    pageTitle: "Find Your Calling",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/calling.png",
    heroImageAlt: "",
    authorName: "Rian Zilca, Ph.D.",
    authorRole: "Author of Ride of Your Life",
    authorAvatar: "/assets/images/Zilca.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Rian Zilca, Ph.D.",
    authorBioShort:
      "Rian Zilca helps people uncover meaningful direction by aligning strengths, values, and long-term goals with day-to-day career choices.",
    authorDescriptionParagraphs: [
      "Many people feel successful on paper but disconnected inside. This track helps you explore your values, motivations, and strengths so your next steps feel meaningful, not just productive.",
      "By combining guided reflection with practical career experiments, you will clarify what kind of work energizes you and how to move toward a path that fits who you are.",
    ],
    authorDescriptionClosing: "Let's move toward work that feels purposeful and fully yours.",
    authorBioFullParagraphs: [
      "Rian Zilca helps people uncover meaningful direction by aligning strengths, values, and long-term goals with day-to-day career choices.",
      "My focus is helping people identify what truly matters to them and translate that insight into realistic, values-aligned career decisions.",
      "I made this track so you can stop guessing about your direction and start making intentional choices that lead to a more meaningful professional life.",
    ],
    helps: [
      "Discover who you are meant to be",
      "Find more meaning in your life",
      "Get closer to the career of your dreams",
    ],
    trackDetails: ["9 Carefully crafted activities"],
  },
};
