/**
 * Track detail content by slug (?track=…). Extend as you add tracks.
 */
window.TRACKS_DATA = {
  "work-burnout": {
    slug: "work-burnout",
    pageTitle: "Find Balance After Work Burnout",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/work-burnout.png",
    heroImageAlt: "",
    authorName: "Saeromi Kim, Ph.D.",
    authorRole: "Clinical Psychologist",
    authorAvatar: "/assets/images/Kim.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by  Saeromi Kim, Ph.D.",
    authorBioShort:
      "Saeromi Kim is an Assistant Clinical Director at UCLA, and also has a private clinical and consultation practice focused on stress, burnout, and sustainable emotional health.",
    authorDescriptionParagraphs: [
      "Let's face it, work can be stressful. So much is out of your control, and the ever-present demands, deadlines, quotas, and uncertainty can leave you feeling worn out.",
      "For both your body and mind, it's important to take the time to reset after a period of intense work stress. It can help replenish your energy and get you back to feeling like yourself—at work, at home, and in your relationships.",
    ],
    authorDescriptionClosing: "Let's get started.",
    authorBioFullParagraphs: [
      "Saeromi Kim is an Assistant Clinical Director at UCLA, and also has a private clinical and consultation practice focused on stress, burnout, and sustainable emotional health.",
      "At UCLA and in private practice, I work with adults who feel stretched thin by work and caregiving responsibilities. My approach blends cognitive behavioral therapy, mindfulness, and self-compassion so progress feels both realistic and sustainable.",
      "I made this track because burnout is not a personal failure; it is often a sign that your system has been overworked for too long. My goal is to help you rebuild rest, resilience, and a sense of agency one step at a time.",
    ],
    helps: [
      "Rest and recover",
      "Feel less stressed and more resilient",
      "Reconnect with joy",
    ],
    trackDetails: ["12 Carefully crafted activities"],
  },
  "beat-burnout-build-resilience": {
    slug: "beat-burnout-build-resilience",
    pageTitle: "Beat Burnout & Build Resilience",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/build-resilience.png",
    heroImageAlt: "",
    authorName: "Emma Seppälä, Ph.D.",
    authorRole: "Author of Track",
    authorAvatar: "/assets/images/Sepa.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Emma Seppala, Ph.D.",
    authorBioShort:
      "Emma Seppala teaches science-backed tools for sustainable performance and emotional resilience at work so high achievement does not come at the cost of well-being.",
    authorDescriptionParagraphs: [
      "Burnout can make every task feel heavier than it should. This track helps you interrupt that cycle by combining practical stress regulation with habits that restore your energy before you hit empty.",
      "You will build small, repeatable routines that support focus, emotional steadiness, and healthier boundaries so your performance can improve without sacrificing your well-being.",
    ],
    authorDescriptionClosing: "Let's build resilience you can actually maintain.",
    authorBioFullParagraphs: [
      "Emma Seppala teaches science-backed tools for sustainable performance and emotional resilience at work so high achievement does not come at the cost of well-being.",
      "My work bridges psychology and leadership, helping people perform at a high level without ignoring their mental and physical health. I care deeply about practical strategies that can fit into real, demanding schedules.",
      "I made this track to help you recover from burnout and build a stronger baseline so stress does not keep dictating how you feel at work and at home.",
    ],
    helps: [
      "Feel less stressed and more fulfilled",
      "Manage your energy better",
      "Maximize your resilience and productivity",
    ],
    trackDetails: ["10 Carefully crafted activities"],
  },
  "thrive-during-change-work": {
    slug: "thrive-during-change-work",
    pageTitle: "Thrive During Change at Work",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/change-work.png",
    heroImageAlt: "",
    authorName: "Taryn Marie, Ph.D.",
    authorRole: "Resilience Expert",
    authorAvatar: "/assets/images/Marie.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Taryn Marie, Ph.D.",
    authorBioShort:
      "Taryn Marie helps teams and professionals stay grounded, adaptable, and purpose-driven during transition, especially when uncertainty impacts confidence and clarity.",
    authorDescriptionParagraphs: [
      "Workplace change can trigger uncertainty, self-doubt, and emotional fatigue. This track gives you a clear process to stay steady when priorities shift and expectations keep moving.",
      "Through structured reflection and resilience exercises, you will learn to reframe difficult dynamics, protect your energy, and reconnect with what matters most in your work.",
    ],
    authorDescriptionClosing: "You can grow through change without losing yourself.",
    authorBioFullParagraphs: [
      "Taryn Marie helps teams and professionals stay grounded, adaptable, and purpose-driven during transition, especially when uncertainty impacts confidence and clarity.",
      "My approach combines evidence-based coping tools with strengths-focused coaching to help people move from reactive stress into intentional action.",
      "I made this track so you have dependable practices for staying clear and grounded even when your workplace environment feels unpredictable.",
    ],
    helps: [
      "Reframe challenging work dynamics",
      "Strengthen resilience during stressful times",
      "Feel more connected to your purpose",
    ],
    trackDetails: ["9 Carefully crafted activities"],
  },
  "find-your-flow-engaged-work": {
    slug: "find-your-flow-engaged-work",
    pageTitle: "Find Your Flow: Feel Engaged at Work",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/engaged-work.png",
    heroImageAlt: "",
    authorName: "Cara Bradley, Ph.D.",
    authorRole: "Author, Body-Mind Teacher",
    authorAvatar: "/assets/images/Bradley.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Cara Bradley, Ph.D.",
    authorBioShort:
      "Cara Bradley blends performance psychology and mindfulness to help people access calm, focused engagement in demanding work environments.",
    authorDescriptionParagraphs: [
      "When your attention is fragmented, work can feel draining and disconnected. This track helps you train your focus and nervous system so you can be present, effective, and less reactive.",
      "You will practice body-mind techniques that reduce stress overload, improve clarity, and support stronger day-to-day performance without constant mental strain.",
    ],
    authorDescriptionClosing: "Let's help you find a steadier, more energized flow state.",
    authorBioFullParagraphs: [
      "Cara Bradley blends performance psychology and mindfulness to help people access calm, focused engagement in demanding work environments.",
      "For years, I have taught practical methods for regulating stress and sharpening attention so people can feel more alive in their work instead of mentally depleted.",
      "I made this track to make flow feel trainable, not accidental, through short practices you can use throughout your workday.",
    ],
    helps: [
      "Increase clarity and calm",
      "Reduce effects of stress on body and mind",
      "Enhance performance",
    ],
    trackDetails: ["8 Carefully crafted activities"],
  },
  "feel-control-working-parent": {
    slug: "feel-control-working-parent",
    pageTitle: "Feel in Control as Working Parent",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/working-parent.png",
    heroImageAlt: "",
    authorName: "Karen Race, Ph.D.",
    authorRole: "Author of Mindful Parenting",
    authorAvatar: "/assets/images/Race.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Karen Race, Ph.D.",
    authorBioShort:
      "Karen Race supports working parents in creating sustainable routines, boundaries, and emotional balance while juggling professional and family demands.",
    authorDescriptionParagraphs: [
      "Balancing career demands and family responsibilities can feel relentless. This track helps you reset your priorities and build practical systems that reduce daily friction.",
      "You will use mindful planning, communication, and boundary-setting tools to create more stability at home and at work so you can feel less pulled in every direction.",
    ],
    authorDescriptionClosing: "Let's make your responsibilities feel manageable again.",
    authorBioFullParagraphs: [
      "Karen Race supports working parents in creating sustainable routines, boundaries, and emotional balance while juggling professional and family demands.",
      "I have spent years supporting families through stress, transition, and role overload. My goal is to turn good intentions into practical routines that actually hold up in busy weeks.",
      "I made this track to help you regain a sense of control while protecting what matters most in both your professional and family life.",
    ],
    helps: [
      "Reconnect with your priorities",
      "Balance your work and family life",
      "Feel less stressed",
    ],
    trackDetails: ["10 Carefully crafted activities"],
  },
  "find-your-calling": {
    slug: "find-your-calling",
    pageTitle: "Find Your Calling",
    categoryBackHref: "category-work-money.html",
    heroImage: "/assets/images/calling.png",
    heroImageAlt: "",
    authorName: "Rian Zilca, Ph.D.",
    authorRole: "Author of Ride of Your Life",
    authorAvatar: "/assets/images/Zilca.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Rian Zilca, Ph.D.",
    authorBioShort:
      "Rian Zilca helps people uncover meaningful direction by aligning strengths, values, and long-term goals with day-to-day career choices.",
    authorDescriptionParagraphs: [
      "Many people feel successful on paper but disconnected inside. This track helps you explore your values, motivations, and strengths so your next steps feel meaningful, not just productive.",
      "By combining guided reflection with practical career experiments, you will clarify what kind of work energizes you and how to move toward a path that fits who you are.",
    ],
    authorDescriptionClosing: "Let's move toward work that feels purposeful and fully yours.",
    authorBioFullParagraphs: [
      "Rian Zilca helps people uncover meaningful direction by aligning strengths, values, and long-term goals with day-to-day career choices.",
      "My focus is helping people identify what truly matters to them and translate that insight into realistic, values-aligned career decisions.",
      "I made this track so you can stop guessing about your direction and start making intentional choices that lead to a more meaningful professional life.",
    ],
    helps: [
      "Discover who you are meant to be",
      "Find more meaning in your life",
      "Get closer to the career of your dreams",
    ],
    trackDetails: ["9 Carefully crafted activities"],
  },
  "rebuild-trust-after-conflict": {
    slug: "rebuild-trust-after-conflict",
    pageTitle: "Rebuild Trust After Conflict",
    categoryBackHref: "category-relationships.html",
    heroImage: "/assets/images/work-burnout.png",
    heroImageAlt: "",
    authorName: "Saeromi Kim, Ph.D.",
    authorRole: "Clinical Psychologist",
    authorAvatar: "/assets/images/Kim.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Saeromi Kim, Ph.D.",
    authorBioShort:
      "Saeromi Kim is an Assistant Clinical Director at UCLA and works with couples and individuals rebuilding trust after emotionally difficult relationship patterns.",
    authorDescriptionParagraphs: [
      "Conflict can create distance quickly, especially when both people feel hurt or misunderstood. This track helps you slow reactive patterns and begin repairing communication with intention.",
      "You will practice concrete trust-building behaviors, emotional regulation, and repair conversations so connection can be rebuilt through consistency rather than promises alone.",
    ],
    authorDescriptionClosing: "Repair is possible when both clarity and care are present.",
    authorBioFullParagraphs: [
      "Saeromi Kim is an Assistant Clinical Director at UCLA and works with couples and individuals rebuilding trust after emotionally difficult relationship patterns.",
      "Her clinical approach integrates attachment-informed therapy, cognitive behavioral tools, and compassion-based communication to help people move from blame toward understanding.",
      "I made this track because many relationships are not lacking love, they are lacking a clear process for repair after rupture. My goal is to give you that process.",
    ],
    helps: [
      "Repair communication after hard moments",
      "Reduce defensiveness and emotional reactivity",
      "Rebuild trust through consistent actions",
    ],
    trackDetails: ["10 Carefully crafted activities"],
  },
  "strengthen-emotional-intimacy": {
    slug: "strengthen-emotional-intimacy",
    pageTitle: "Strengthen Emotional Intimacy",
    categoryBackHref: "category-relationships.html",
    heroImage: "/assets/images/build-resilience.png",
    heroImageAlt: "",
    authorName: "Emma Seppälä, Ph.D.",
    authorRole: "Author of Track",
    authorAvatar: "/assets/images/Sepa.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Emma Seppala, Ph.D.",
    authorBioShort:
      "Emma Seppala studies connection and emotional resilience, helping partners build closeness through everyday habits that feel authentic and sustainable.",
    authorDescriptionParagraphs: [
      "Emotional intimacy is built through repeated small moments, not one big conversation. This track helps you create those moments through intentional listening, warmth, and emotional presence.",
      "You will learn how to express needs with clarity, respond with empathy, and cultivate routines that strengthen closeness even during stressful weeks.",
    ],
    authorDescriptionClosing: "Lasting intimacy grows from everyday practice.",
    authorBioFullParagraphs: [
      "Emma Seppala studies connection and emotional resilience, helping partners build closeness through everyday habits that feel authentic and sustainable.",
      "Her work bridges psychology and behavior change, focusing on small shifts that increase emotional safety and mutual understanding over time.",
      "I made this track because people often wait for the perfect moment to reconnect, when what truly works is creating consistent moments of care in ordinary life.",
    ],
    helps: [
      "Feel more connected in everyday interactions",
      "Express needs with clarity and warmth",
      "Create moments of closeness that last",
    ],
    trackDetails: ["9 Carefully crafted activities"],
  },
  "navigate-difficult-conversations": {
    slug: "navigate-difficult-conversations",
    pageTitle: "Navigate Difficult Conversations",
    categoryBackHref: "category-relationships.html",
    heroImage: "/assets/images/change-work.png",
    heroImageAlt: "",
    authorName: "Taryn Marie, Ph.D.",
    authorRole: "Resilience Expert",
    authorAvatar: "/assets/images/Marie.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Taryn Marie, Ph.D.",
    authorBioShort:
      "Taryn Marie helps people approach high-stakes conversations with more calm, confidence, and structure so hard topics do not become relationship dead ends.",
    authorDescriptionParagraphs: [
      "Difficult conversations can escalate quickly when fear, assumptions, or old triggers take over. This track gives you a practical framework for preparing and communicating with steadiness.",
      "You will build skills for emotional regulation, precise language, and collaborative problem-solving so difficult discussions lead to understanding rather than further distance.",
    ],
    authorDescriptionClosing: "Hard conversations can become turning points.",
    authorBioFullParagraphs: [
      "Taryn Marie helps people approach high-stakes conversations with more calm, confidence, and structure so hard topics do not become relationship dead ends.",
      "Her work emphasizes resilience under stress and communication tools that protect dignity while still addressing what matters.",
      "I made this track because many relationships struggle not from lack of care, but from not knowing how to speak honestly without creating more harm.",
    ],
    helps: [
      "Prepare for high-stakes relationship talks",
      "Stay calm while discussing hard topics",
      "Reach clearer, more respectful outcomes",
    ],
    trackDetails: ["8 Carefully crafted activities"],
  },
  "set-healthy-boundaries-confidence": {
    slug: "set-healthy-boundaries-confidence",
    pageTitle: "Set Healthy Boundaries with Confidence",
    categoryBackHref: "category-relationships.html",
    heroImage: "/assets/images/engaged-work.png",
    heroImageAlt: "",
    authorName: "Cara Bradley, Ph.D.",
    authorRole: "Author, Body-Mind Teacher",
    authorAvatar: "/assets/images/Bradley.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Cara Bradley, Ph.D.",
    authorBioShort:
      "Cara Bradley teaches body-mind awareness to help people notice overload early and communicate boundaries clearly before resentment builds.",
    authorDescriptionParagraphs: [
      "Without clear boundaries, even caring relationships can become draining. This track helps you recognize your limits sooner and communicate them in ways that preserve respect and connection.",
      "You will learn to identify stress signals, set practical limits, and follow through consistently so your relationships feel healthier and more balanced.",
    ],
    authorDescriptionClosing: "Boundaries protect connection when they are clear and compassionate.",
    authorBioFullParagraphs: [
      "Cara Bradley teaches body-mind awareness to help people notice overload early and communicate boundaries clearly before resentment builds.",
      "Her approach combines nervous-system regulation with practical communication habits so people can say what they need without shutting others out.",
      "I made this track because many people believe boundaries create conflict, when in reality they often prevent it and make relationships safer for everyone.",
    ],
    helps: [
      "Protect your energy without guilt",
      "Communicate limits in a respectful way",
      "Build relationships with clearer expectations",
    ],
    trackDetails: ["9 Carefully crafted activities"],
  },
  "reconnect-parenting-partners": {
    slug: "reconnect-parenting-partners",
    pageTitle: "Reconnect as Parenting Partners",
    categoryBackHref: "category-relationships.html",
    heroImage: "/assets/images/working-parent.png",
    heroImageAlt: "",
    authorName: "Karen Race, Ph.D.",
    authorRole: "Author of Mindful Parenting",
    authorAvatar: "/assets/images/Race.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Karen Race, Ph.D.",
    authorBioShort:
      "Karen Race supports co-parents in reducing stress, improving teamwork, and restoring a sense of partnership in family life.",
    authorDescriptionParagraphs: [
      "Parenting stress can push partners into logistics mode, leaving less room for understanding and emotional support. This track helps you rebuild teamwork and reconnect around shared values.",
      "You will practice communication rhythms, role clarity, and conflict de-escalation tools so everyday family decisions feel more collaborative and less exhausting.",
    ],
    authorDescriptionClosing: "Strong parenting partnerships are built intentionally, not accidentally.",
    authorBioFullParagraphs: [
      "Karen Race supports co-parents in reducing stress, improving teamwork, and restoring a sense of partnership in family life.",
      "Her work centers on mindful parenting, emotional attunement, and practical systems that help families function with less friction.",
      "I made this track because parenting pressure can quietly erode connection between partners, and small coordinated changes can make a profound difference.",
    ],
    helps: [
      "Strengthen teamwork in family decisions",
      "Reduce conflict around routines and roles",
      "Support each other with more empathy",
    ],
    trackDetails: ["10 Carefully crafted activities"],
  },
  "build-deeper-friendships": {
    slug: "build-deeper-friendships",
    pageTitle: "Build Deeper Friendships",
    categoryBackHref: "category-relationships.html",
    heroImage: "/assets/images/calling.png",
    heroImageAlt: "",
    authorName: "Rian Zilca, Ph.D.",
    authorRole: "Author of Ride of Your Life",
    authorAvatar: "/assets/images/Zilca.png",
    authorAvatarAlt: "",
    authorCreatedLabel: "Created by Rian Zilca, Ph.D.",
    authorBioShort:
      "Rian Zilca helps people create more meaningful social connection by aligning how they show up in friendships with the values they care about most.",
    authorDescriptionParagraphs: [
      "Many friendships stay on the surface even when both people want more depth. This track helps you move from occasional contact to consistent, meaningful connection.",
      "You will practice vulnerability, intentional outreach, and mutual support habits that strengthen trust and create friendships that feel nourishing over time.",
    ],
    authorDescriptionClosing: "Deep friendship grows through courage, consistency, and care.",
    authorBioFullParagraphs: [
      "Rian Zilca helps people create more meaningful social connection by aligning how they show up in friendships with the values they care about most.",
      "His work focuses on purpose, belonging, and practical behavior change so relationships reflect what matters most rather than convenience alone.",
      "I made this track because friendship is one of the strongest predictors of well-being, yet many people need clearer guidance for building it intentionally.",
    ],
    helps: [
      "Create stronger mutual support",
      "Move from surface talk to real connection",
      "Nurture friendships that feel meaningful",
    ],
    trackDetails: ["8 Carefully crafted activities"],
  },
};
